version: '3.3'

services:
  backend_monitoring:
    build: .
    container_name: backend_monitoring
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    env_file: .env
    networks:
      - vant-network
    volumes:
      - ./:/code

networks:
  vant-network:
    name: vant-network
    driver: bridge